version: '3'

services:
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - TZ=Europe/Moscow
        ports:
            - '5432:5432'
        volumes:
            - postgres:/var/lib/postgresql/data:cached

    mysql:
        image: harbor.ispring.lan/vendor/percona-server:8.0.29-21-ispring7
        environment:
            - MYSQL_DATABASE=benchmark
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_HOST=%
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        ports:
            - '33306:3306' # non-standard port exposed, to avoid clash with locally installed MySQL for example
        volumes:
            - mysql:/var/lib/mysql:cached

volumes:
    postgres: null
    mysql: null
